# Generated by Django 4.2.6 on 2023-10-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='video',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follow',
        ),
    ]
